# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170729_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeOfToll',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('codeColor', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='typeOfToll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.typeOfToll'),
            preserve_default=False,
        ),
    ]
