# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-29 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170729_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='typeOfToll',
            new_name='TypeOfTool',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='typeOfToll',
            new_name='typeOfTool',
        ),
    ]
