# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170729_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typeoftool',
            name='canonical',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
