# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170729_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushFoward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='typeoftool',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tool',
            name='pushFowardBoolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tool',
            name='pushFowar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.PushFoward'),
            preserve_default=False,
        ),
    ]
