# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20170729_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='pushFowar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.PushFoward'),
        ),
    ]
