# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-29 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='pushFowar',
            new_name='pushFoward',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='typeOfTool',
        ),
        migrations.AddField(
            model_name='tool',
            name='typeOfTool',
            field=models.ManyToManyField(to='project.TypeOfTool'),
        ),
    ]
